## 强制转换
`Number()`
`String()`
`Boolean()`

### Number()
`Number`函数将字符串转为数值，要比`parseInt`函数严格很多。基本上，只要有一个字符无法转成数值，整个字符串就会被转为NaN。

`parseInt`和`Number`函数都会自动过滤一个字符串前导和后缀的空格。

`Number`方法的参数是对象时，将返回`NaN`，除非是包含单个数值的数组

### String()
- 数值：转为相应的字符串。
- 字符串：转换后还是原来的值。
- 布尔值：`true`转为字符串`"true"`，`false`转为字符串`"false"`。
- `undefined`：转为字符串`"undefined"`。
- `null`：转为字符串`"null"`。

String方法的参数如果是对象，返回一个类型字符串；如果是数组，返回该数组的字符串形式。
```javascript
String({a: 1}) // "[object Object]"
String([1, 2, 3]) // "1,2,3"
```
### Boolean()
`Boolean`函数可以将任意类型的值转为布尔值。

它的转换规则相对简单：除了以下五个值的转换结果为`false`，其他的值全部为`true`。

- `undefined`
- `null`
- `-0`或`+0`
- `NaN`
- `''`（空字符串）

## 错误处理机制

`Error`实例对象是最一般的错误类型，在它的基础上
还存在`Error`的6个派生对象

### SyntaxError(语法错误) 对象
`SyntaxError`对象是解析代码时发生的语法错误。

### ReferenceError(参考错误) 对象
`ReferenceError`对象是引用一个不存在的变量时发生的错误。

### RangeError(范围错误) 对象
`RangeError`对象是一个值超出有效范围时发生的错误。主要有几种情况，一是数组长度为负数，二是Number对象的方法参数超出范围，以及函数堆栈超过最大值。

### TypeError(类型错误) 对象
`TypeError`对象是变量或参数不是预期类型时发生的错误。比如，
1. 对字符串、布尔值、数值等原始类型的值使用new命令，就会抛出这种错误，因为new命令的参数应该是一个构造函数。
2. 调用对象不存在的方法，也会抛出TypeError错误，

### URIError 对象
`URIError`对象是 URI 相关函数的参数不正确时抛出的错误，主要涉及
- `encodeURI()`、	把字符串编码为 URI。
- `decodeURI()`、解码某个编码的 URI。
- `encodeURIComponent()`、把字符串编码为 URI 组件。
- `decodeURIComponent()`、解码一个编码的 URI 组件。
- `escape()`、对字符串进行编码。
- `unescape()` 对由 escape() 编码的字符串进行解码。
这六个函数。
`URI` 统一资源标识符（Uniform Resource Identifier，或URI)是一个用于标识某一互联网资源名称的字符串
`URL` 统一资源定位符,是URI的子集
`URN` 统一资源名称,是URI的子集

### EvalError 对象
eval函数没有被正确执行时，会抛出EvalError错误。
~~该错误类型已经不再使用了，只是为了保证与以前代码兼容，才继续保留。~~

## 自定义错误
除了 JavaScript 原生提供的七种错误对象，还可以定义自己的错误对象。
```javascript
function UserError(message) {
  this.message = message || '默认信息';
  this.name = 'UserError';
}

UserError.prototype = new Error();
UserError.prototype.constructor = UserError; // 重新将原型指向自己
new UserError('这是自定义的错误！');
```
上面代码自定义一个错误对象UserError，让它继承Error对象。然后，就可以生成这种自定义类型的错误了。

## throw 语句
`throw`语句的作用是手动中断程序执行，抛出一个错误。`throw`可以抛出任何类型的值。也就是说，它的参数可以是任何值。

## try...catch 结构
如果try中抛出错误，catch会捕获到try抛出的错误继续向下执行
```javascript
try {
  throw "出错了";
} catch (e) {
  console.log(111);
}
console.log(222);
// 111
// 222
```
## finally 代码块
`try...catch`结构允许在最后添加一个`finally`代码块，表示不管是否出现错误，都必需在最后运行的语句

如果没有`catch`语句块，一旦发生错误，代码就会中断执行。中断执行之前，会先执行`finally`代码块，然后再向用户提示报错信息。

`try`里的`return`语句的执行是排在`finally`代码之前，只是等`finally`代码执行完毕后才返回。


## 语法规则

一般`tab`缩进

一般使用大写表示全局变量, 如`UPPER_CASE`

不要使用`with`语句

只使用严格相等运算符（`===`）

`++x` 等同于 `x += 1`

## console 对象与控制台

建议switch...case结构可以用对象结构代替。
```javascript
// console 对象
// console 对象的静态方法
console.log()
console.info()
console.debug()
console.warn()
console.error()

console.table()
console.count()

console.dir()
console.dirxml()

console.assert()

console.time()
console.timeEnd()

console.group()
console.groupEnd()
console.groupCollapsed()

console.trace()
console.clear()
// 控制台命令行 API
debugger 语句
```
